# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
brand: Rottenberg Therapy
title: Rottenberg Therapy - New York City based therapy for individuals and couples
email: sary@rottenbergtherapy.com
description: >- # this means to ignore newlines until "baseurl:"
  Sary Rottenberg Psychotherapy provides therapy to individuals and couples in New York City and surrounding areas. We specialize in and treat relationships, career changes, trauma, depression, anxiety as well as issues affecting the LGBTQ community.
baseurl: / # the subpath of your site, e.g. /blog
url: "http://www.rottenbergtherapy.com"
address: 245 W 29th St, New York, NY 10001
plugins:
  - jekyll-sitemap
  - jekyll-loading-lazy
  - jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-172086252          
    anonymizeIp: false
# Build settings
include: [_pages]
markdown: kramdown
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  [node_modules, Gemfile, Gemfile.lock, vendor/bundle/, vendor/cache/, vendor/gems, vendor/ruby/]
livereload: true
