individuals:
  blurb: |-
    Our Integrative approach drawing from psychodynamic, cognitive behavioral, strengths-based and mindfulness practices, tailoring to and honoring your unique needs.
relationship counseling:
  blurb: |-
    The special set of challenges that comes with romantic relationships are addressed bringing to light patterns of communications, and needs that are asked to be met.